### ISSUE TITLE
请问如何在 SublimeLinter 中启用 standard

### ISSUE THREAD

**Issue by clinyong** [leecade/es6-study#2]
需要在文件 `SublimeLinter.sublime-settings` 配置什么吗

**Comment by leecade** [comment]
启用就好了

Sublime 菜单里

Tools > SublimeLinter > Toggle Linter 

![image](https://cloud.githubusercontent.com/assets/533360/11159151/50267b2c-8a98-11e5-8db9-4a199d8e073a.png)

`standard` 目前为止感觉非常棒, 简单稳定, 唯一一些小问题比如, 不允许变量定义但不使用; react html-like 片段仍然必须用单引号

**Comment by clinyong** [comment]
谢谢答复，`standard` 确实很不错，之前配置 `eslint` 一直没成功。还有一个问题就是，用 `standard formt` 的时候，为什么每次格式化的时候 `sublime` 都会很卡。我是用 winodws，ST3。

**Comment by leecade** [comment]
`standard-formt` osx 下没有觉得很卡呢, 或者你觉得保存时很卡不流畅, 就设置手动 format

这个插件就是一个问题不支持 npm install local 之前提给作者, 不知道现在修了没
